# Generated by Django 2.1.2 on 2018-11-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20181105_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='pushover_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
