# Generated by Django 2.1.2 on 2018-11-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_usersettings_pushover_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notify_via_mail',
            field=models.BooleanField(default=False, verbose_name='Notify via email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='pushover_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pushover User Key'),
        ),
    ]
